// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcvoarsvjtympiflbgyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjdm9hcnN2anR5bXBpZmxiZ3l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTc4MTcsImV4cCI6MjA2NDY5MzgxN30.AxZG8MdBKn1jrm3shJcfNAAdoI_Yb_-wpEv_SiEd_Kg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);