// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqzrjcmeoykinnqwmurl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxenJqY21lb3lraW5ucXdtdXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDYxODgsImV4cCI6MjA2NDQyMjE4OH0.bEbQ2bHR8GYzRh0SamkkYekeArHD-wAfbasiBBjEEt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);