// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpxknltghrlinkingjhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxweGtubHRnaHJsaW5raW5namhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjM5MDYsImV4cCI6MjA2NDU5OTkwNn0.oCaGDMomffiS2M7PX_IoOit0zIARzA6Cv6VWV-Wl7Ug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);